runtime: nodejs8

env_variables:
  NODE_ENV: production

handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto

  - url: /favicon.ico
    static_files: build/favicon.ico
    upload: build/favicon.ico
