import { fs } from "../../firebase";

/**
 * Register a new user
 *
 * @param {*} param0 - Signin form data
 * @param {*} uid - UID generated by google auth
 */
export const postUser = (
  { username, name, email, photo, description, cover, isChecked },
  uid
) => {
  return fs
    .collection(`users`)
    .doc(uid)
    .set({
      name,
      username,
      email,
      photo,
      cover,
      isChecked,
      description
    })
    .then(() => {
      return uid;
    });
};

/**
 * Get a specific user
 * TODO: why this is duplicated?
 *
 * @param {*} param0 - uid
 */
export const get = ({ uid }) =>
  fs
    .collection(`users`)
    .doc(uid)
    .get();

/**
 * Get a specific user
 *
 * @param {*} param0 - uid
 */
export const getUser = ({ uid }) => {
  return fs
    .collection(`users`)
    .doc(uid)
    .get();
};

/**
 * Get session followers
 *
 * @param {*} param0
 */
export const getFollowers = ({ uid }) => {
  return fs
    .collection(`users`)
    .doc(uid)
    .collection(`followers`)
    .get();
};

/**
 * List users that session follow
 */
export const getFollowing = ({ uid }) => {
  return fs
    .collection(`users`)
    .doc(uid)
    .collection(`following`)
    .get();
};

export const update = ({ uid }, data) => {
  return fs
    .collection(`users`)
    .doc(uid)
    .update(data);
};
